In [2]:
import pandas as pd

In [6]:
df = pd.read_parquet("scenario_001.parquet")

In [12]:
list(df.columns)

['df',
 'squawk',
 'bds60_bds',
 'bds60_heading',
 'bds60_IAS',
 'bds60_Mach',
 'bds60_vrate_barometric',
 'bds60_vrate_inertial',
 'icao24',
 'ts',
 'bds',
 'NACv',
 'groundspeed',
 'track',
 'vrate_src',
 'vertical_rate',
 'geo_minus_baro',
 'tc',
 'NUCp',
 'NICb',
 'altitude',
 'source',
 'parity',
 'lat_cpr',
 'lon_cpr',
 'lat_deg',
 'lon_deg',
 'bds40_bds',
 'bds40_selected_mcp',
 'bds40_barometric_setting',
 'bds40_selected_fms',
 'selected_altitude',
 'barometric_setting',
 'NACp',
 'tcas_operational',
 'bds50_bds',
 'bds50_roll',
 'bds50_track',
 'bds50_groundspeed',
 'bds50_track_rate',
 'bds50_TAS',
 'version',
 'NICa',
 'GVA',
 'SIL',
 'BAI',
 'HRD',
 'SILs',
 'bds45_bds',
 'bds45_turbulence',
 'bds45_wind_shear',
 'bds45_microburst',
 'bds45_icing',
 'bds45_wake_vortex',
 'bds45_static_temperature',
 'bds45_static_pressure',
 'bds45_radio_height',
 'tisb',
 'id',
 'wake_vortex',
 'callsign',
 'TAH',
 'selected_heading',
 'bds20_bds',
 'bds20_callsign',
 'subtype',
 'emergency_state',
 'bds05_tc',
 'bds05_NUCp',
 'bds05_NICb',
 'bds05_altitude',
 'bds05_source',
 'bds05_parity',
 'bds05_lat_cpr',
 'bds05_lon_cpr',
 'bds10_bds',
 'bds10_config',
 'bds10_ovc',
 'bds10_acas',
 'bds10_subnet',
 'bds10_level5',
 'bds10_mode_s',
 'bds10_identification',
 'bds10_squitter',
 'bds10_sic',
 'bds10_gicb',
 'bds10_acas_hybrid',
 'bds10_acas_ra',
 'bds10_dte',
 'bds17_bds',
 'bds17_bds05',
 'bds17_bds06',
 'bds17_bds07',
 'bds17_bds08',
 'bds17_bds09',
 'bds17_bds0a',
 'bds17_bds20',
 'bds17_bds40',
 'bds17_bds50',
 'bds17_bds51',
 'bds17_bds52',
 'bds17_bds5f',
 'bds17_bds60',
 'autopilot',
 'vnav_mode',
 'alt_hold',
 'approach_mode',
 'lnav_mode',
 'bds44_bds',
 'bds44_wind_speed',
 'bds44_wind_direction',
 'bds44_temperature',
 'bds44_pressure',
 'bds44_turbulence',
 'bds44_humidity',
 'bds17_bds21',
 'bds17_bds53',
 'TAS',
 'heading',
 'bds17_bds41',
 'bds17_bds42',
 'bds17_bds44',
 'bds17_bds48',
 'bds21_bds',
 'bds21_registration',
 'bds40_target_source',
 'bds17_bds45',
 'bds17_bds54',
 'bds17_bds55',
 'bds17_bds56',
 'year',
 'month',
 'day',
 'hour']

In [14]:
df

,df,squawk,bds60_bds,bds60_heading,bds60_IAS,bds60_Mach,bds60_vrate_barometric,bds60_vrate_inertial,icao24,ts,...,bds21_registration,bds40_target_source,bds17_bds45,bds17_bds54,bds17_bds55,bds17_bds56,year,month,day,hour
0,20,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,3c618b,1741503722828,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,3,9,7
1,20,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,347256,1741503722828,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,3,9,7
2,17,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,3451d8,1741503722828,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,3,9,7
3,20,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,4952c6,1741503722828,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,3,9,7
4,21,5045,60,187.734375,256.0,0.724,-192.0,0.0,347256,1741503722828,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,3,9,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48023,20,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,39d301,1741503842694,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,3,9,7
48024,21,0470,60,229.218750,251.0,0.776,0.0,0.0,34620c,1741503842694,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,3,9,7
48025,21,5763,<NA>,NaN,NaN,NaN,NaN,NaN,4b1a2a,1741503842694,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,3,9,7
48026,17,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,34134e,1741503842694,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,3,9,7
48027,21,3775,60,225.527344,266.0,0.784,-256.0,0.0,4b18b8,1741503842729,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2025,3,9,7